// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"pvesphere/internal/handler"
	"pvesphere/internal/job"
	"pvesphere/internal/repository"
	"pvesphere/internal/router"
	"pvesphere/internal/server"
	"pvesphere/internal/service"
	"pvesphere/pkg/app"
	"pvesphere/pkg/jwt"
	"pvesphere/pkg/log"
	"pvesphere/pkg/server/http"
	"pvesphere/pkg/sid"

	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	pveClusterRepository := repository.NewPveClusterRepository(repositoryRepository)
	pveClusterService := service.NewPveClusterService(serviceService, pveClusterRepository, repositoryRepository, logger)
	pveAuthHandler := handler.NewPveAuthHandler(handlerHandler, pveClusterService)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	pveClusterHandler := handler.NewPveClusterHandler(handlerHandler, pveClusterService)
	pveNodeRepository := repository.NewPveNodeRepository(repositoryRepository)
	pveNodeService := service.NewPveNodeService(serviceService, pveNodeRepository, pveClusterRepository, logger)
	pveNodeHandler := handler.NewPveNodeHandler(handlerHandler, pveNodeService)
	pveVMRepository := repository.NewPveVMRepository(repositoryRepository)
	vmTemplateRepository := repository.NewVmTemplateRepository(repositoryRepository)
	templateInstanceRepository := repository.NewTemplateInstanceRepository(repositoryRepository)
	pveStorageRepository := repository.NewPveStorageRepository(repositoryRepository)
	vmipAddressRepository := repository.NewVMIPAddressRepository(repositoryRepository)
	pveVMService := service.NewPveVMService(serviceService, pveVMRepository, vmTemplateRepository, templateInstanceRepository, pveStorageRepository, vmipAddressRepository, pveClusterRepository, pveNodeRepository, logger)
	pveVMHandler := handler.NewPveVMHandler(handlerHandler, pveVMService)
	pveStorageService := service.NewPveStorageService(serviceService, pveStorageRepository, pveNodeRepository, logger)
	pveStorageHandler := handler.NewPveStorageHandler(handlerHandler, pveStorageService)
	pveTemplateRepository := repository.NewPveTemplateRepository(repositoryRepository)
	templateUploadRepository := repository.NewTemplateUploadRepository(repositoryRepository)
	templateSyncTaskRepository := repository.NewTemplateSyncTaskRepository(repositoryRepository)
	pveTemplateService := service.NewPveTemplateService(serviceService, pveTemplateRepository, templateInstanceRepository, templateSyncTaskRepository, templateUploadRepository, pveNodeRepository, pveClusterRepository, logger)
	pveTemplateHandler := handler.NewPveTemplateHandler(handlerHandler, pveTemplateService)
	templateManagementService := service.NewTemplateManagementService(serviceService, pveTemplateRepository, templateUploadRepository, templateInstanceRepository, templateSyncTaskRepository, pveVMRepository, pveStorageRepository, pveNodeRepository, pveClusterRepository, logger)
	templateManagementHandler := handler.NewTemplateManagementHandler(handlerHandler, templateManagementService)
	pveTaskService := service.NewPveTaskService(serviceService, pveClusterRepository, logger)
	pveTaskHandler := handler.NewPveTaskHandler(handlerHandler, pveTaskService)
	dashboardService := service.NewDashboardService(serviceService, pveClusterRepository, pveNodeRepository, pveVMRepository, pveStorageRepository, logger)
	dashboardHandler := handler.NewDashboardHandler(handlerHandler, dashboardService)
	routerDeps := router.RouterDeps{
		Logger:                    logger,
		Config:                    viperViper,
		JWT:                       jwtJWT,
		PveAuthHandler:            pveAuthHandler,
		UserHandler:               userHandler,
		PveClusterHandler:         pveClusterHandler,
		PveNodeHandler:            pveNodeHandler,
		PveVMHandler:              pveVMHandler,
		PveStorageHandler:         pveStorageHandler,
		PveTemplateHandler:        pveTemplateHandler,
		TemplateManagementHandler: templateManagementHandler,
		PveTaskHandler:            pveTaskHandler,
		DashboardHandler:          dashboardHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewPveClusterRepository, repository.NewPveNodeRepository, repository.NewPveVMRepository, repository.NewPveStorageRepository, repository.NewVmTemplateRepository, repository.NewVMIPAddressRepository, repository.NewPveTemplateRepository, repository.NewTemplateUploadRepository, repository.NewTemplateInstanceRepository, repository.NewTemplateSyncTaskRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewPveClusterService, service.NewPveNodeService, service.NewPveVMService, service.NewPveStorageService, service.NewPveTemplateService, service.NewPveTaskService, service.NewDashboardService, service.NewTemplateManagementService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewPveAuthHandler, handler.NewUserHandler, handler.NewPveClusterHandler, handler.NewPveNodeHandler, handler.NewPveVMHandler, handler.NewPveStorageHandler, handler.NewPveTemplateHandler, handler.NewTemplateManagementHandler, handler.NewPveTaskHandler, handler.NewDashboardHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("demo-server"))
}
