// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"pvesphere/internal/controller"
	"pvesphere/internal/repository"
	"pvesphere/internal/server"
	"pvesphere/pkg/app"
	"pvesphere/pkg/log"
	"time"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	pveClusterRepository := repository.NewPveClusterRepository(repositoryRepository)
	pveNodeRepository := repository.NewPveNodeRepository(repositoryRepository)
	pveVMRepository := repository.NewPveVMRepository(repositoryRepository)
	pveStorageRepository := repository.NewPveStorageRepository(repositoryRepository)
	duration := _wireDurationValue
	pveController := controller.NewPveController(pveClusterRepository, pveNodeRepository, pveVMRepository, pveStorageRepository, logger, duration)
	controllerServer := server.NewControllerServer(logger, pveController)
	appApp := newApp(controllerServer)
	return appApp, func() {
	}, nil
}

var (
	_wireDurationValue = time.Minute *
		5
)

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewPveClusterRepository, repository.NewPveNodeRepository, repository.NewPveVMRepository, repository.NewPveStorageRepository, repository.NewVMIPAddressRepository, repository.NewVmTemplateRepository)

var controllerSet = wire.NewSet(controller.NewPveController)

var serverSet = wire.NewSet(server.NewControllerServer)

func newApp(
	controllerServer *server.ControllerServer,
) *app.App {
	return app.NewApp(app.WithServer(controllerServer), app.WithName("pve-controller"))
}
